[build]
  command = "npm install --include=dev --ignore-scripts ; node node_modules/@rsbuild/core/bin/rsbuild.js build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
